### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by raufis27** [markusressel/sunix-ledstrip-controller-client#1]
Hello,
Does your code support any Sunix controller or there is specific one ?

I am looking to buy this controller - [https://www.amazon.com/Sunix-Flexible-Controller-Channels-Control/dp/B075X8TJCD/ref=pd_day0_86_4?_encoding=UTF8&pd_rd_i=B075X8TJCD&pd_rd_r=23KCK47PC0EPT4X19ZN3&pd_rd_w=3G7mm&pd_rd_wg=Vkj2S&psc=1&refRID=23KCK47PC0EPT4X19ZN3](url)

**Comment by markusressel** [comment]
I don't know about the controller you linked but I can tell you which one I use:

https://www.amazon.de/gp/aw/d/B01J5A7ABW

I got four of those in my apartment and they work pretty reliably.

It may very well be that the one you linked uses the same protocol but I simply don't know.

**Comment by raufis27** [comment]
Thanks for quick response. One more question, which mobile app your controller uses ? Controller you use is not available in us store. The new one we have, has different app called S Panel, not Magic Home. Can you try S Panel from App Store and see if it works with for you, this way I'll know that API is the same. 

Thank you!

**Comment by markusressel** [comment]
I just tested the S Panel app with my controllers and it works out of the box. The S Panel app also looks like a visual overhaul of the Magic Home app with almost the same layout.

Of course there is still the slight possibility that they have implemented multiple different protocols in the newer S Panel app so I can't guarantee you that it will work - but the chances are high.

**Comment by raufis27** [comment]
Thanks a lot! I'll get controller and report back.

**Comment by markusressel** [comment]
Any update on this?

**Comment by raufis27** [comment]
Yes, that controller is compatible with your code! Thank you!

**Comment by markusressel** [comment]
Great! Thanks for testing and letting us know :)
